/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import data.DataRepository;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import util.BDLocal;
import modelo.Plato;
import modelo.Promocion;
import modelo.Resultado;

/**
 *
 * @author OMAR
 */
public class CartaVista extends javax.swing.JInternalFrame {

    private List<Plato> carta;

    /**
     * Creates new form Entradas
     * @param title
     * @param tipo
     */
    public CartaVista(String title, String tipo) {
        initComponents();
        this.setSize(new Dimension(600, 660));
        this.setTitle(title);
        jLabel1.setText(title);
        obtenerPromociones(tipo);

    }

    private void obtenerPromociones(String tipo) {
        new SwingWorker<Resultado<List<Plato>>, Void>() {
            @Override
            protected Resultado<List<Plato>> doInBackground() throws Exception {
                return DataRepository.obtenerPlatosPorTipo(tipo);
            }

            @Override
            protected void done() {
                super.done();
                System.err.println("obtenido");
                Resultado<List<Plato>> resultado = null;
                try {
                    resultado = get();
                    carta = resultado.getData();

                    jPanel5.setLayout(new GridLayout(0, 2, 10, 10));

                    for (Plato menu : carta) {
                        PlatoVista item = new PlatoVista(menu);
                        item.setSize(new Dimension(254, 266));
                        jPanel5.add(item);
                    }
                    jPanel5.revalidate();
                    if (carta.isEmpty()) {
                        System.err.println("vacio");
                    } else {
                        System.err.println("mostrando");

                    }
                } catch (InterruptedException | ExecutionException ex) {
                    ex.printStackTrace();

                    Logger.getLogger(InicioCliente.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(242, 184, 128));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("- ENTRADAS -");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1);

        jPanel5.setLayout(new java.awt.GridLayout(4, 2));
        jScrollPane1.setViewportView(jPanel5);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
