/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author salaz
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 12), new java.awt.Dimension(0, 12), new java.awt.Dimension(32767, 12));
        jPanel4 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(null, null, new java.awt.Dimension(16, 0));
        jButton4 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0));
        jLabel3 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 12), new java.awt.Dimension(0, 12), new java.awt.Dimension(32767, 12));
        jPanel2 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 12), new java.awt.Dimension(0, 12), new java.awt.Dimension(32767, 12));
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(89, 63, 40));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(filler1);

        jPanel4.setBackground(null);
        jPanel4.setForeground(new java.awt.Color(230, 208, 165));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler4);

        jButton4.setBackground(null);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close_24dp_E6D0A5_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jPanel4.add(jButton4);
        jPanel4.add(filler2);

        jLabel3.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 208, 165));
        jLabel3.setText("RESTAURANT LA BUENA SARTEN");
        jLabel3.setMaximumSize(null);
        jLabel3.setMinimumSize(null);
        jLabel3.setPreferredSize(null);
        jPanel4.add(jLabel3);

        jPanel5.add(jPanel4);
        jPanel5.add(filler3);

        jPanel2.setBackground(null);
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler5);

        jButton1.setBackground(null);
        jButton1.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(230, 208, 165));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/restaurant_24dp_E6D0A5_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton1.setText("Inicio");
        jButton1.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jPanel2.add(jButton1);

        jSeparator1.setMaximumSize(new java.awt.Dimension(3, 3));
        jSeparator1.setPreferredSize(new java.awt.Dimension(3, 3));
        jPanel2.add(jSeparator1);

        jButton2.setBackground(null);
        jButton2.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(230, 208, 165));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu_book_24dp_E6D0A5_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton2.setText("Menu");
        jButton2.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jPanel2.add(jButton2);

        jSeparator2.setMaximumSize(new java.awt.Dimension(3, 3));
        jPanel2.add(jSeparator2);

        jButton3.setBackground(null);
        jButton3.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(230, 208, 165));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/local_dining_24dp_E6D0A5_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton3.setText("Reservaciones");
        jButton3.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jPanel2.add(filler6);

        jPanel5.add(jPanel2);
        jPanel5.add(filler7);
        jPanel5.add(jTabbedPane1);

        getContentPane().add(jPanel5);

        setSize(new java.awt.Dimension(1400, 837));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ReservasRestaurante().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
