/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import data.UserRepository;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import modelo.Resultado;
import modelo.Usuario;
import util.FontLoader;
import util.UserUtil;
import util.ViewUtil;
import view.CustomLabel;

/**
 *
 * @author cristopher
 */
public class LoginUser extends javax.swing.JFrame {

    /**
     * Creates new form LoginUser
     */
    public LoginUser() {
        Usuario usuario = UserUtil.getUsuario();

        if(usuario == null) iniciar();
        else new Principal(usuario).setVisible(true);
        
    }
    
    final void iniciar() {
        initComponents();
        CustomLabel coverLabel = new CustomLabel("/resources/promo1.jpg");
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(coverLabel, BorderLayout.CENTER);
        jProgressBar1.setVisible(false);
        setTitle("Iniciar Sesión como usuario");
        ViewUtil.cambiarFuente(jPanel4,JLabel.class, "Poppins-SemiBold.ttf", 14, new Color(186,158,104));
        ViewUtil.cambiarFuente(jPanel4,JTextField.class, "Poppins-SemiBold.ttf", 14, new Color(100,100,100));
        jLabel1.setFont(FontLoader.load("Poppins-Black.ttf", Font.PLAIN, 32));
        jButton2.setFont(FontLoader.load("Poppins-SemiBold.ttf", Font.PLAIN, 14));
        jButton1.setFont(FontLoader.load("Poppins-SemiBold.ttf", Font.PLAIN, 14));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textContrasena = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1200, 900));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setSize(new java.awt.Dimension(1200, 900));
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setBackground(null);
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 32, 1, 32));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(filler1);

        jPanel3.setBackground(null);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Noto Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(186, 158, 104));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesion");
        jLabel1.setAlignmentX(0.5F);
        jPanel3.add(jLabel1);

        jPanel4.setBackground(null);
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 208, 165));
        jLabel2.setLabelFor(textCorreo);
        jLabel2.setText("Correo Electronico");
        jPanel4.add(jLabel2);

        textCorreo.setBorder(null);
        jPanel4.add(textCorreo);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 208, 165));
        jLabel3.setText("Contraseña");
        jPanel4.add(jLabel3);

        textContrasena.setEchoChar('*');
        jPanel4.add(textContrasena);

        jPanel3.add(jPanel4);

        jPanel5.add(jPanel3);

        jPanel6.setBackground(null);
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 1, 1, 1));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jButton1.setBackground(new java.awt.Color(186, 158, 104));
        jButton1.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");
        jButton1.setAlignmentX(0.5F);
        jButton1.setMargin(new java.awt.Insets(8, 14, 8, 14));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jLabel4.setText("ó");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        jPanel6.add(jLabel4);

        jButton2.setBackground(new java.awt.Color(186, 158, 104));
        jButton2.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CrearCuenta");
        jButton2.setMargin(new java.awt.Insets(8, 14, 8, 14));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jPanel5.add(jPanel6);

        jProgressBar1.setForeground(new java.awt.Color(186, 158, 104));
        jProgressBar1.setIndeterminate(true);
        jPanel5.add(jProgressBar1);
        jPanel5.add(filler2);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new NewUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String correo = ViewUtil.verificarMinimo(textCorreo, 1, "Es necesario completar el correo electrónico.");
        String contrasena = ViewUtil.verificarMinimo(textContrasena, 1, "Es necesario completar la contraseña.");
        
        if(correo == null || contrasena == null) return;
        
        
        ViewUtil.setComponentsEnabled(jPanel4, false);
        jProgressBar1.setVisible(true);
        new SwingWorker<Resultado<Usuario>, Void>() {
             
            @Override
            protected Resultado<Usuario> doInBackground() throws Exception {
                return  UserRepository.login(correo, contrasena);
            }

            @Override
            protected void done() {
                super.done();
                try {
                    Resultado<Usuario> resultado = get();
                    ViewUtil.setComponentsEnabled(jPanel4, true);
                    jProgressBar1.setVisible(false);
                    ViewUtil.vaciarInputs(jPanel4);
               if(resultado.isOk()) {
                        JOptionPane.showMessageDialog(null, "Bienvenido");
                        Usuario usuario = resultado.getData();
                        UserUtil.guardarUsuario(usuario);

                        dispose(); // cerrar login

                       // if (usuario.getTipoUsuario().getDescripcion().equalsIgnoreCase("Administrador")) {
                      //      new VistaAdmin().setVisible(true);
                       // } else {
                            new Principal(usuario).setVisible(true);
                        //}
                    }

                    else {
                        JOptionPane.showMessageDialog(null, resultado.getMessage());
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(LoginUser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    Logger.getLogger(LoginUser.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            
            
        }.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPasswordField textContrasena;
    private javax.swing.JTextField textCorreo;
    // End of variables declaration//GEN-END:variables
}
