/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import view.CustomLabel;

/**
 *
 * @author cristopher
 */
public class LoginU extends javax.swing.JFrame {

    /**
     * Creates new form LoginUser
     */
    public LoginU() {
        initComponents();
        CustomLabel coverLabel = new CustomLabel("/resources/bg.png");
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(coverLabel, BorderLayout.CENTER);
        
        // Configurar tamaño y posición
            this.setSize(new Dimension(1000,700));
            this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(8, 32767));
        jPanel5 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 0));
        jPanel6 = new javax.swing.JPanel();
        btt_ingresar = new javax.swing.JButton();
        btt_IrCrearCuenta = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(8, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1200, 900));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(null);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 900));
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(89, 63, 40));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));
        jPanel2.add(filler5);

        jPanel5.setBackground(null);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(filler1);

        jPanel3.setBackground(null);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Noto Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 208, 165));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesion");
        jLabel1.setAlignmentX(0.5F);
        jPanel3.add(jLabel1);

        jPanel4.setBackground(null);
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 208, 165));
        jLabel2.setLabelFor(txt_correo);
        jLabel2.setText("Correo Electronico");
        jPanel4.add(jLabel2);
        jPanel4.add(txt_correo);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 208, 165));
        jLabel3.setText("Contraseña");
        jPanel4.add(jLabel3);
        jPanel4.add(txt_contraseña);

        jPanel3.add(jPanel4);
        jPanel3.add(filler3);

        jPanel6.setBackground(null);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        btt_ingresar.setBackground(null);
        btt_ingresar.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        btt_ingresar.setForeground(new java.awt.Color(230, 208, 165));
        btt_ingresar.setText("Ingresar");
        btt_ingresar.setAlignmentX(0.5F);
        btt_ingresar.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btt_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_ingresarActionPerformed(evt);
            }
        });
        jPanel6.add(btt_ingresar);

        btt_IrCrearCuenta.setBackground(null);
        btt_IrCrearCuenta.setFont(new java.awt.Font("Noto Serif", 0, 15)); // NOI18N
        btt_IrCrearCuenta.setForeground(new java.awt.Color(230, 208, 165));
        btt_IrCrearCuenta.setText("CrearCuenta");
        btt_IrCrearCuenta.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btt_IrCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_IrCrearCuentaActionPerformed(evt);
            }
        });
        jPanel6.add(btt_IrCrearCuenta);

        jPanel3.add(jPanel6);

        jPanel5.add(jPanel3);
        jPanel5.add(filler2);

        jPanel2.add(jPanel5);
        jPanel2.add(filler4);

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btt_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_ingresarActionPerformed
        this.Menu();
    }//GEN-LAST:event_btt_ingresarActionPerformed

    private void btt_IrCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_IrCrearCuentaActionPerformed
        this.CrearCuenta();
    }//GEN-LAST:event_btt_IrCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_IrCrearCuenta;
    private javax.swing.JButton btt_ingresar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_correo;
    // End of variables declaration//GEN-END:variables
    
    private void Menu() {
        try {
            Principal menu = new Principal();
            menu.setVisible(true);
            
            // Cerrar la ventana actual de login
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error al abrir la ventana de Menu: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al abrir el menú: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void CrearCuenta(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Crear y mostrar la ventana de Inicio
                    NewUser nuevo = new NewUser();
                    nuevo.setVisible(true);
                    
                    // Cerrar la ventana actual de login
                    LoginU.this.dispose();
                } catch (Exception e) {
                    e.printStackTrace();
                    System.out.println("Error al abrir la ventana de Inicio: " + e.getMessage());
                }
            }
        });
    }
}
