/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import modelo.Mesa;
import util.FontLoader;
import view.ImagePanel;

/**
 *
 * @author cristopher
 */
public class MesaVista extends javax.swing.JPanel {
    private final OnSelectedListener onSelectedListener;
    private final Mesa mesa;
    
    /**
     * Creates new form MesaVista
     */
    public MesaVista(Mesa mesa, OnSelectedListener onSelectedListener, boolean seleccionado) {
        initComponents();
        this.onSelectedListener = onSelectedListener;
        this.mesa = mesa;
        setOpaque(false);
        String image = "";
        
        switch (mesa.getCapacidad()) {
            case 2 -> image = "seats_2.png";
            case 4 -> image = "seats_4.png";
            case 6 -> image = "seats_6.png";
            case 8 -> image = "seats_8.png";
            case 10 -> image = "seats_10.png";                
        }
        ImagePanel imagePanel = new ImagePanel(image, ImagePanel.FitMode.CONTAIN);
        imagePanel.setBackground(Color.WHITE);
        imagePanel.setBorder(new EmptyBorder(8,8,8,8));
        textId.setFont(FontLoader.load("Poppins-SemiBold.ttf", 16));
        textCapacidad.setFont(FontLoader.load("Poppins-Regular.ttf", 14));
        textId.setText("Mesa n° " + mesa.getNumeroMesa());
        textCapacidad.setForeground(mesa.isDisponible() ? Color.GREEN : Color.RED);
        textCapacidad.setText(mesa.isDisponible() ? "Disponible" : "Ya reservada");
        panelCtn.add(imagePanel, BorderLayout.CENTER);
        if(seleccionado) {
            jPanel2.setBorder(new LineBorder(Color.GREEN, 3, true));
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelCtn = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        textId = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        textCapacidad = new javax.swing.JLabel();

        setForeground(new java.awt.Color(204, 255, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClick(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler1);

        panelCtn.setLayout(new java.awt.BorderLayout());
        add(panelCtn);
        add(filler4);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        textId.setText("jLabel1");
        textId.setAlignmentX(0.5F);
        jPanel1.add(textId);
        jPanel1.add(filler2);

        textCapacidad.setText("jLabel2");
        textCapacidad.setAlignmentX(0.5F);
        jPanel1.add(textCapacidad);

        jPanel2.add(jPanel1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void onClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClick
        // TODO add your handling code here:
        onSelectedListener.onSelect(mesa);
    }//GEN-LAST:event_onClick

    public static interface OnSelectedListener {
        void onSelect(Mesa mesa);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCtn;
    private javax.swing.JLabel textCapacidad;
    private javax.swing.JLabel textId;
    // End of variables declaration//GEN-END:variables
}
