/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import data.DataRepository;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import modelo.Novedad;
import modelo.Promocion;
import modelo.Resultado;
import util.FontLoader;

/**
 *
 * @author OMAR
 */
public class Promos extends javax.swing.JInternalFrame {

    private List<Promocion> novedades;

    public Promos() {
        initComponents();
        this.setTitle("Promociones");
        jLabel1.setFont(FontLoader.load("Poppins-Black.ttf", Font.PLAIN, 20));
        obtenerPromociones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelLista = new javax.swing.JPanel();

        setBackground(new java.awt.Color(242, 184, 128));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1200, 630));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("- Promos -");
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1188, Short.MAX_VALUE)
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelLista);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerPromociones() {
        new SwingWorker<Resultado<List<Promocion>>, Void>() {
            @Override
            protected Resultado<List<Promocion>> doInBackground() throws Exception {
                return DataRepository.obtenerPromociones();
            }

            @Override
            protected void done() {
                super.done();
                Resultado<List<Promocion>> resultado = null;
                try {
                    resultado = get();
                    novedades = resultado.getData();
                    if (novedades.isEmpty()) {
                    } else {
                        mostrarPromociones();
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    Logger.getLogger(InicioCliente.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }.execute();
    }

    void mostrarPromociones() {
        int columnas = 2;
        int filas = (int) Math.ceil(novedades.size() / (double) columnas);

        panelLista.setLayout(new GridLayout(filas, columnas, 10, 10));

        for (Promocion novedad : novedades) {
            PromocionVista vista = new PromocionVista(novedad);
            panelLista.add(vista);
        }
        panelLista.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelLista;
    // End of variables declaration//GEN-END:variables
}
