/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Font;
import modelo.Promocion;
import util.FontLoader;
import view.ImagePanel;

/**
 *
 * @author cristopher
 */
public class PromocionVista extends javax.swing.JPanel {

    /**
     * Creates new form NovedadVista
     * @param novedad
     */
    public PromocionVista(Promocion novedad) {
        initComponents();
        txtTitulo.setText(novedad.getTitulo());
        txtTitulo.setFont(FontLoader.load("Poppins-Black.ttf", Font.PLAIN, 20));

        panelImagen.removeAll();
        ImagePanel imagen = new ImagePanel(novedad.getImageUrl(), ImagePanel.FitMode.CONTAIN);
        imagen.setAlignmentX(0.5f);
        imagen.setAlignmentY(0.5f);
        panelImagen.add(imagen, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        panelImagen = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 32, 16, 32));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        txtTitulo.setText("jLabel1");
        add(txtTitulo);

        panelImagen.setLayout(new java.awt.BorderLayout());
        add(panelImagen);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelImagen;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
