/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import data.DataRepository;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.SwingWorker;
import modelo.Promocion;
import modelo.Reserva;
import modelo.Resultado;
import modelo.Usuario;
import util.FontLoader;
import util.UserUtil;

/**
 *
 * @author Gian Marrufo
 */
public class ReservasRestaurante extends javax.swing.JFrame {

    private List<Reserva> reservas;

    /**
     * Creates new form ReservasRestaurante
     */
    public ReservasRestaurante() {
        initComponents();

        obtenerReservas();
        labelTitle.setFont(FontLoader.load("Poppins-Black.ttf", Font.PLAIN, 20));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMesas = new javax.swing.JPanel();
        panelEmpty = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elija la mesa a reservar");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 32, 16, 32));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        labelTitle.setText("Mis Reservaciones");
        jPanel1.add(labelTitle);

        getContentPane().add(jPanel1);

        jScrollPane1.setAlignmentX(0.0F);

        panelMesas.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 36, 0, 36));
        panelMesas.setLayout(new javax.swing.BoxLayout(panelMesas, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelMesas);

        getContentPane().add(jScrollPane1);

        panelEmpty.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32));
        panelEmpty.setAlignmentX(0.0F);
        panelEmpty.setMaximumSize(null);
        panelEmpty.setPreferredSize(new java.awt.Dimension(9999, 120));
        panelEmpty.setLayout(new javax.swing.BoxLayout(panelEmpty, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText("Actualmente no tienens ninguna reservacion.");
        panelEmpty.add(jLabel2);

        getContentPane().add(panelEmpty);

        setSize(new java.awt.Dimension(689, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerReservas() {
        new SwingWorker<Resultado<List<Reserva>>, Void>() {
            @Override
            protected Resultado<List<Reserva>> doInBackground() throws Exception {
                Usuario usuario = UserUtil.getUsuario();
                return DataRepository.obtenerReservasDeUsuario(usuario.getIdUsuario());
            }

            @Override
            protected void done() {
                super.done();
                Resultado<List<Reserva>> resultado = null;
                try {
                    resultado = get();
                    reservas = resultado.getData();
                    if (reservas.isEmpty()) {
                        panelEmpty.setVisible(true);
                    } else {
                        panelEmpty.setVisible(false);
                        mostrarReservas();
                    }
                } catch (InterruptedException | ExecutionException ex) {
                    Logger.getLogger(InicioCliente.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }.execute();
    }

    public void mostrarReservas() {
        panelMesas.setLayout(new GridLayout(reservas.size(), 1));
        for(Reserva reserva : reservas) {
            ReservaVista vistaReserva = new ReservaVista(reserva);
            panelMesas.add(vistaReserva);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelEmpty;
    private javax.swing.JPanel panelMesas;
    // End of variables declaration//GEN-END:variables
}
