/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Font;
import modelo.Reserva;
import util.FontLoader;

/**
 *
 * @author cristopher
 */
public class ReservaVista extends javax.swing.JPanel {

    /**
     * Creates new form ReservaVista
     */
    public ReservaVista(Reserva reserva) {
        initComponents();
        jLabel1.setFont(FontLoader.load("Poppins-SemiBold.ttf", Font.PLAIN, 14));
        jLabel3.setFont(FontLoader.load("Poppins-SemiBold.ttf", Font.PLAIN, 14));

        jLabel5.setFont(FontLoader.load("Poppins-SemiBold.ttf", Font.PLAIN, 14));

        jLabel7.setFont(FontLoader.load("Poppins-SemiBold.ttf", Font.PLAIN, 14));

        jLabel9.setFont(FontLoader.load("Poppins-SemiBold.ttf", Font.PLAIN, 14));

        labelEstado.setFont(FontLoader.load("Poppins-Regular.ttf", Font.PLAIN, 14));
        labelFecha.setFont(FontLoader.load("Poppins-Regular.ttf", Font.PLAIN, 14));
        labelHora.setFont(FontLoader.load("Poppins-Regular.ttf", Font.PLAIN, 14));
        labelMesa.setFont(FontLoader.load("Poppins-Regular.ttf", Font.PLAIN, 14));
        labelPersonas.setFont(FontLoader.load("Poppins-Regular.ttf", Font.PLAIN, 14));
        
        labelEstado.setText(reserva.getEstado());
        labelPersonas.setText("" +reserva.getCantPersonas());
        labelMesa.setText("Mesa " + reserva.getMesa().getNumeroMesa());
        labelFecha.setText(reserva.getFechaReserva().toString());
        labelHora.setText(reserva.getHoraReserva().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelMesa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelPersonas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelFecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelHora = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelEstado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setAlignmentX(0.0F);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("Mesa");
        jPanel1.add(jLabel1);
        jPanel1.add(filler1);

        labelMesa.setText("jLabel2");
        jPanel1.add(labelMesa);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setText("N° personas");
        jPanel2.add(jLabel3);
        jPanel2.add(filler2);

        labelPersonas.setText("jLabel2");
        jPanel2.add(labelPersonas);

        add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jLabel5.setText("Fecha");
        jPanel3.add(jLabel5);
        jPanel3.add(filler3);

        labelFecha.setText("jLabel2");
        jPanel3.add(labelFecha);

        add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jLabel7.setText("Hora");
        jPanel4.add(jLabel7);
        jPanel4.add(filler4);

        labelHora.setText("jLabel2");
        jPanel4.add(labelHora);

        add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jLabel9.setText("Estado");
        jPanel5.add(jLabel9);
        jPanel5.add(filler5);

        labelEstado.setText("jLabel2");
        jPanel5.add(labelEstado);

        add(jPanel5);
        add(jSeparator1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelMesa;
    private javax.swing.JLabel labelPersonas;
    // End of variables declaration//GEN-END:variables
}
